version: "3.9"

services:
  web:
    build: .
    container_name: pi_flask
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
      - PORT=5000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=INFO
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    container_name: pi_celery_worker
    command: celery -A app.celery_app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: pi_redis
    ports:
      - "6379:6379"
